---
title: "10-Load-Data"
output: html_notebook
---


Load data file
*written for windows PC*
```{r}
data=read.csv(file="./datasets/LC3-B4_PD_Jan2019/beta4_LC3B-PD-quant_16Jan23.csv", header=TRUE)
```


Calculating means and Standard deviation
```{r}

data$AveLC3B<-NA

data$SDLC3B<-NA

for (t in c("NoB4", "B4")) {
  data$AveLC3B[which(data$Type==t)]<-sum(data$relLC3B[which(data$Type==t & data$relLC3B)])/length(which(data$Type==t & data$relLC3B))
}



for (t in c("NoB4", "B4")) {
  data$SDLC3B[which(data$Type==t)]<-sd(data$relLC3B[which(data$Type==t & data$relLC3B)])
}

```

Calculating means and Standard deviation-ATG9A
```{r}

data$AveATG9<-NA
data$SDATG9<-NA

for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  data$AveATG9[which(data$Type==t)]<-sum(data$relWTATG9A[which(data$Type==t & data$relWTATG9A)])/length(which(data$Type==t & data$relWTATG9A))
}



for (t in c("WT", "Control", "tepsin", "AP4E1")) {
  data$SDATG9[which(data$Type==t)]<-sd(data$relWTATG9A[which(data$Type==t & data$relWTATG9A)])
}

```

Remove duplicate rows from replicates
```{r}
data_nodup<-data[!duplicated(data$AveLC3B),]
```

